/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.form;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.ssh.POJO.Genealogy;
import com.ssh.common.DateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 09-21-2018
 * 
 * XDoclet definition:
 * @struts.form name="modifyGenealogyForm"
 */
public class ModifyGenealogyForm extends ActionForm {
	/*
	 * Generated fields
	 */

	Logger log = LoggerFactory.getLogger(ModifyGenealogyForm.class);
	
	/** birthday property */
	private String birthday;

	
	private String name;
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/** sex property */
	private Integer sex;

	/** other property */
	private String other;

	/** remark property */
	private String remark;

	/** characteristi property */
	private String characteristi;

	/** dateOfDeath property */
	private String dateOfDeath;

	/** photo property */
	private String photo;

	/** father property */
	private String father;

	/** resume property */
	private String resume;

	/** mother property */
	private String mother;

	/** zid property */
	private String zid;

	/** userId property */
	private Integer userId;

	/** ancestryId property */
	private String ancestryId;

	/** sheetName property */
	private String sheetName;

	/** place property */
	private String place;

	
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the birthday.
	 * @return Date
	 */
	public String getBirthday() {
		
		
		return birthday;
	}

	/** 
	 * Set the birthday.
	 * @param birthday The birthday to set
	 */
	public void setBirthday(String birthday) {
		
		this.birthday = birthday;
	}

	/** 
	 * Returns the sex.
	 * @return Integer
	 */
	public Integer getSex() {
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/** 
	 * Returns the other.
	 * @return String
	 */
	public String getOther() {
		return other;
	}

	/** 
	 * Set the other.
	 * @param other The other to set
	 */
	public void setOther(String other) {
		this.other = other;
	}

	/** 
	 * Returns the remark.
	 * @return String
	 */
	public String getRemark() {
		return remark;
	}

	/** 
	 * Set the remark.
	 * @param remark The remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/** 
	 * Returns the characteristi.
	 * @return String
	 */
	public String getCharacteristi() {
		return characteristi;
	}

	/** 
	 * Set the characteristi.
	 * @param characteristi The characteristi to set
	 */
	public void setCharacteristi(String characteristi) {
		this.characteristi = characteristi;
	}

	/** 
	 * Returns the dateOfDeath.
	 * @return Date
	 */
	public String getDateOfDeath() {
		return dateOfDeath;
	}

	/** 
	 * Set the dateOfDeath.
	 * @param dateOfDeath The dateOfDeath to set
	 */
	public void setDateOfDeath(String dateOfDeath) {
		this.dateOfDeath = dateOfDeath;
	}

	/** 
	 * Returns the photo.
	 * @return String
	 */
	public String getPhoto() {
		return photo;
	}

	/** 
	 * Set the photo.
	 * @param photo The photo to set
	 */
	public void setPhoto(String photo) {
		this.photo = photo;
	}

	/** 
	 * Returns the father.
	 * @return String
	 */
	public String getFather() {
		return father;
	}

	/** 
	 * Set the father.
	 * @param father The father to set
	 */
	public void setFather(String father) {
		this.father = father;
	}

	/** 
	 * Returns the resume.
	 * @return String
	 */
	public String getResume() {
		return resume;
	}

	/** 
	 * Set the resume.
	 * @param resume The resume to set
	 */
	public void setResume(String resume) {
		this.resume = resume;
	}

	/** 
	 * Returns the mother.
	 * @return String
	 */
	public String getMother() {
		return mother;
	}

	/** 
	 * Set the mother.
	 * @param mother The mother to set
	 */
	public void setMother(String mother) {
		this.mother = mother;
	}

	/** 
	 * Returns the zid.
	 * @return String
	 */
	public String getZid() {
		return zid;
	}

	/** 
	 * Set the zid.
	 * @param zid The zid to set
	 */
	public void setZid(String zid) {
		this.zid = zid;
	}

	/** 
	 * Returns the userId.
	 * @return Integer
	 */
	public Integer getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the ancestryId.
	 * @return String
	 */
	public String getAncestryId() {
		return ancestryId;
	}

	/** 
	 * Set the ancestryId.
	 * @param ancestryId The ancestryId to set
	 */
	public void setAncestryId(String ancestryId) {
		this.ancestryId = ancestryId;
	}

	/** 
	 * Returns the sheetName.
	 * @return String
	 */
	public String getSheetName() {
		return sheetName;
	}

	/** 
	 * Set the sheetName.
	 * @param sheetName The sheetName to set
	 */
	public void setSheetName(String sheetName) {
		this.sheetName = sheetName;
	}

	/** 
	 * Returns the place.
	 * @return String
	 */
	public String getPlace() {
		return place;
	}

	/** 
	 * Set the place.
	 * @param place The place to set
	 */
	public void setPlace(String place) {
		this.place = place;
	}
	
	
	public void update(Genealogy genealogy){
		this.zid = genealogy.getZid();
		this.userId = genealogy.getUserId();
		this.name = genealogy.getName();
		this.sheetName = genealogy.getSheetName();
		this.sex = genealogy.getSex();
		
		;
		String birthdayStr =DateUtil.dateToString(genealogy.getBirthday(), DateUtil.YYYY_MM_DD);
		this.birthday = birthdayStr;
		
		this.father = genealogy.getFather();
		this.mother = genealogy.getMother();
		this.characteristi = genealogy.getCharacteristi();
		this.place = genealogy.getPlace();
		this.ancestryId = genealogy.getAncestryId();
		this.photo = genealogy.getPhoto();
		
		String dateOfDeathStr = DateUtil.dateToString(genealogy.getDateOfDeath(), DateUtil.YYYY_MM_DD);
		this.dateOfDeath = dateOfDeathStr;
		
		this.resume = genealogy.getResume();
		this.remark = genealogy.getRemark();
		this.other = genealogy.getOther();
	}
}