/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-07-2018
 * 
 * XDoclet definition:
 * @struts.form name="searchPandaForm"
 */
public class SearchPandaForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** mother property */
	private String mother;

	/** zid property */
	private String zid;

	/** name property */
	private String name;

	/** ansestryId property */
	private String ansestryId;

	/** father property */
	private String father;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the mother.
	 * @return String
	 */
	public String getMother() {
		return mother;
	}

	/** 
	 * Set the mother.
	 * @param mother The mother to set
	 */
	public void setMother(String mother) {
		this.mother = mother;
	}

	/** 
	 * Returns the zid.
	 * @return String
	 */
	public String getZid() {
		return zid;
	}

	/** 
	 * Set the zid.
	 * @param zid The zid to set
	 */
	public void setZid(String zid) {
		this.zid = zid.trim();
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the ansestryId.
	 * @return String
	 */
	public String getAnsestryId() {
		return ansestryId;
	}

	/** 
	 * Set the ansestryId.
	 * @param ansestryId The ansestryId to set
	 */
	public void setAnsestryId(String ansestryId) {
		this.ansestryId = ansestryId;
	}

	/** 
	 * Returns the father.
	 * @return String
	 */
	public String getFather() {
		return father;
	}

	/** 
	 * Set the father.
	 * @param father The father to set
	 */
	public void setFather(String father) {
		this.father = father;
	}
}