/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-21-2018
 * 
 * XDoclet definition:
 * @struts.form name="searchGenealogyForm"
 */
public class SearchGenealogyForm extends ActionForm {
	/*
	 * Generated fields
	 */

	
	private String name;
	
	/** mother property */
	private String mother;

	/** zid property */
	private String zid;

	/** userId property */
	private Integer userId;

	/** sheetName property */
	private String sheetName;

	/** father property */
	private String father;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
	
	/** 
	 * Returns the mother.
	 * @return String
	 */
	public String getMother() {
		return mother;
	}

	/** 
	 * Set the mother.
	 * @param mother The mother to set
	 */
	public void setMother(String mother) {
		this.mother = mother;
	}

	/** 
	 * Returns the zid.
	 * @return String
	 */
	public String getZid() {
		return zid;
	}

	/** 
	 * Set the zid.
	 * @param zid The zid to set
	 */
	public void setZid(String zid) {
		this.zid = zid;
	}

	/** 
	 * Returns the userId.
	 * @return Integer
	 */
	public Integer getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the sheetName.
	 * @return String
	 */
	public String getSheetName() {
		return sheetName;
	}

	/** 
	 * Set the sheetName.
	 * @param sheetName The sheetName to set
	 */
	public void setSheetName(String sheetName) {
		this.sheetName = sheetName;
	}

	/** 
	 * Returns the father.
	 * @return String
	 */
	public String getFather() {
		return father;
	}

	/** 
	 * Set the father.
	 * @param father The father to set
	 */
	public void setFather(String father) {
		this.father = father;
	}
}