/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-14-2018
 * 
 * XDoclet definition:
 * @struts.form name="showYYForm"
 */
public class ShowYYForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** birthday property */
	private String birthday;

	/** nother property */
	private String nother;

	/** name property */
	private String name;

	/** pid property */
	private String zid2;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the birthday.
	 * @return String
	 */
	public String getBirthday() {
		return birthday;
	}

	/** 
	 * Set the birthday.
	 * @param birthday The birthday to set
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	/** 
	 * Returns the nother.
	 * @return String
	 */
	public String getNother() {
		return nother;
	}

	/** 
	 * Set the nother.
	 * @param nother The nother to set
	 */
	public void setNother(String nother) {
		this.nother = nother;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the pid.
	 * @return String
	 */
	public String getZid2() {
		return zid2;
	}

	/** 
	 * Set the pid.
	 * @param pid The pid to set
	 */
	public void setZid2(String zid2) {
		this.zid2 = zid2;
	}
}