/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.action;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;

import com.ssh.POJO.Genealogy;
import com.ssh.common.DateUtil;
import com.ssh.common.MessageAndFlag;
import com.ssh.service.GenealogyService;
import com.ssh.struts.form.ModifyGenealogyForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-21-2018
 * 
 * XDoclet definition:
 * @struts.action path="/addGenealogy" name="addGenealogyForm" input="/form/addGenealogy.jsp" scope="request" validate="true"
 * @struts.action-forward name="searchGenealogy" path="/jsp/searchGenealogy.jsp"
 */

@Controller("/addGenealogy")
public class AddGenealogyAction extends Action {
	/*
	 * Generated Methods
	 */

	Logger log = LoggerFactory.getLogger(AddGenealogyAction.class);
	
	@Autowired
	@Qualifier("genealogyService")
	private GenealogyService genealogyService;
	
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ModifyGenealogyForm genealogyForm = (ModifyGenealogyForm) form;// TODO Auto-generated method stub
		String sheetName = genealogyForm.getSheetName();
		String name = genealogyForm.getName();
		Integer userId = 1;//以后从session护着application中获取
		Integer sex = genealogyForm.getSex();
		String father = genealogyForm.getFather();
		String mother = genealogyForm.getMother();
		String ancestryId = genealogyForm.getAncestryId();
		String characteristi = genealogyForm.getCharacteristi();
		String place = genealogyForm.getPlace();
		String photo = genealogyForm.getPhoto();
		String birthdayStr = genealogyForm.getBirthday();
		String dateOfDeathStr = genealogyForm.getDateOfDeath();
		String resume = genealogyForm.getResume();
		String remark = genealogyForm.getRemark();
		String other = genealogyForm.getOther();
		if(null == userId || userId == 0){
			userId = 1;//后续改为从session中获取
		}
		
		Date birthday = null;
		try {
			birthday = DateUtil.stringToDateCommon(birthdayStr);
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			log.info("birthdayStr("+birthdayStr+") 格式在DateUtil中不存在  输入正确格式yyyy-MM-dd" );
			e.printStackTrace();
		}
		Date dateOfDeath = null;
		try {
			dateOfDeath = DateUtil.stringToDateCommon(dateOfDeathStr);
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			log.info("dateOfDeathStr("+dateOfDeathStr+") 格式在DateUtil中不存在  输入正确格式yyyy-MM-dd" );
			e.printStackTrace();
		}
		
		Genealogy genealogy = new Genealogy(null,userId,name,sheetName,sex,birthday,father,mother,characteristi,place,ancestryId,photo,dateOfDeath,resume,remark,other);
		
		
		
		MessageAndFlag mf = genealogyService.saveOrUpdateGenealogy(genealogy);
		request.setAttribute("message", mf.getMessage());
		if(mf.isFlag()){
			
			log.info("add Genealogy success");
			return mapping.findForward("searchGenealogy");
			
		}
		//以后改为本页
		log.info("add Genealogy fail:"+mf.getMessage());
		return mapping.findForward("searchGenealogy");
		
		
		
	}
}