/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;

import com.ssh.service.ShowYYService;
import com.ssh.struts.form.CoupleForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-22-2018
 * 
 * XDoclet definition:
 * @struts.action path="/couple" name="coupleForm" input="/jsp/couple.jsp" scope="request" validate="true"
 */
@Controller("/couple")
public class CoupleAction extends Action {
	/*
	 * Generated Methods
	 */
	@Autowired
	@Qualifier("showYYService")
	ShowYYService showYYService;
	
	public void setShowYYService(ShowYYService showYYService) {
		this.showYYService = showYYService;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CoupleForm coupleForm = (CoupleForm) form;// TODO Auto-generated method stub
		String id = coupleForm.getId();
		String otherId = coupleForm.getOtherId();
		String name = coupleForm.getName();
		String otherName = coupleForm.getOtherName();
		
		
		if(id.isEmpty() || otherId.isEmpty()){
			request.setAttribute("message", "id不能为空");
			return mapping.findForward("isCouple");
		}
		String iscp = showYYService.isCouple(id,otherId);
		
		request.setAttribute("message", "".equals(iscp)?"三代内没有血缘关系，可以组cp":iscp);
		if(true){
			return mapping.findForward("isCouple");
		}
		
		return null;
	}
}