/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.action;

import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;

import com.ssh.POJO.Genealogy;
import com.ssh.common.MessageAndFlag;
import com.ssh.service.GenealogyService;
import com.ssh.struts.form.ModifyGenealogyForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-21-2018
 * 
 * XDoclet definition:
 * @struts.action path="/modifyGenealogy" name="modifyGenealogyForm" input="/jsp/modifyGenealogy.jsp" scope="request" validate="true"
 * @struts.action-forward name="searchGenealogy" path="/jsp/searchGenealogy.jsp"
 */
@Controller("/deleteGenealogy")
public class DeleteGenealogyAction extends Action {
	/*
	 * Generated Methods
	 */

	@Autowired
	@Qualifier("genealogyService")
	private GenealogyService genealogyService;
	
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ModifyGenealogyForm genealogyForm = (ModifyGenealogyForm) form;// TODO Auto-generated method stub
		
		String zid = request.getParameter("zid");
		if(null == zid || zid.isEmpty()){
			request.setAttribute("message", "zid("+zid+")为空，请正确输入");
			return mapping.findForward("searchGenealogy");
		}
		
		if(genealogyService.deleteGenealogy(zid)){
			request.setAttribute("message", "zid("+zid+") delete success");
		}
		else{
			request.setAttribute("message", "zid("+zid+") delete fail");
		}
		//以后改为本页
		
		return mapping.findForward("searchGenealogy");
	}
}