/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;

import com.ssh.POJO.Panda;
import com.ssh.common.Global;
import com.ssh.service.SearchPandaService;
import com.ssh.struts.form.ModifyPandaForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-07-2018
 * 
 * XDoclet definition:
 * @struts.action path="/modifyPanda" name="modifyPandaForm" input="/jsp/modifyPanda.jsp" scope="request" validate="true"
 */
@Controller("/modifyPanda")
public class ModifyPandaAction extends Action {
	/*
	 * Generated Methods
	 */
	
	@Autowired
	@Qualifier("pandaService")
	SearchPandaService searchPandaService = new SearchPandaService();
	private static final Logger log = LoggerFactory.getLogger(SearchPandaService.class);
	
	public void setSps(SearchPandaService searchPandaService) {
		this.searchPandaService = searchPandaService;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ModifyPandaForm modifyPandaForm = (ModifyPandaForm) form;// TODO Auto-generated method stub
		String zid = modifyPandaForm.getZid();
		String name = modifyPandaForm.getName();
		String birthday = modifyPandaForm.getBirthday();
		if(searchPandaService == null){
			log.info("searchPandaService is null,create from Global");
			searchPandaService = (SearchPandaService) Global.getBean("searchPandaService");
		}
		Panda panda = modifyPandaForm.getPanda();
		searchPandaService.modifyPanda(panda);
		return mapping.findForward("showPanda");
	}
}