/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.action;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;

import com.ssh.POJO.Genealogy;
import com.ssh.common.DateUtil;
import com.ssh.common.MessageAndFlag;
import com.ssh.service.GenealogyService;
import com.ssh.struts.form.ModifyGenealogyForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-21-2018
 * 
 * XDoclet definition:
 * @struts.action path="/modifyGenealogy" name="modifyGenealogyForm" input="/jsp/modifyGenealogy.jsp" scope="request" validate="true"
 * @struts.action-forward name="searchGenealogy" path="/jsp/searchGenealogy.jsp"
 */
@Controller("/modifyGenealogyByZid")
public class ModifyGenealogByIdyAction extends Action {
	/*
	 * Generated Methods
	 */

	@Autowired
	@Qualifier("genealogyService")
	private GenealogyService genealogyService;
	
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ModifyGenealogyForm genealogyForm = (ModifyGenealogyForm) form;// TODO Auto-generated method stub
		
		String zid = request.getParameter("zid");
		if(null == zid || zid.isEmpty()){
			request.setAttribute("message", "zid("+zid+")为空，请正确输入");
			return mapping.findForward("searchGenealogy");
		}
		Genealogy genealogy = new Genealogy();
		genealogy.setZid(zid);
		List<Genealogy> gList = genealogyService.getGenealogys(genealogy);
		if(null == gList || gList.size() == 0){
			request.setAttribute("message", "zid("+zid+")对应的数据为空");
			return mapping.findForward("searchGenealogy");
		}
		//以后改为本页
		
		ModifyGenealogyForm genealogyFormTemp = new ModifyGenealogyForm();
		genealogyFormTemp.update(gList.get(0));
		
		request.setAttribute("genealogy", genealogyFormTemp);
		
		/**  genealogyFormTemp.update(gList.get(0)) 在update方法中加入了daetorString
		Date birthday = gList.get(0).getBirthday();
		Date dateOfDeath = gList.get(0).getDateOfDeath();
		String birthdayStr = DateUtil.dateToString(birthday, DateUtil.YYYY_MM_DD);
		String dateOfDeathStr = DateUtil.dateToString(dateOfDeath, DateUtil.YYYY_MM_DD);;
		
		request.setAttribute("birthday", birthdayStr);
		
		request.setAttribute("dateOfDeath", dateOfDeathStr);
		*/
		return mapping.findForward("modifyGenealogy");
	}
}