/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;

import com.ssh.POJO.Panda;
import com.ssh.service.SearchPandaService;
import com.ssh.struts.form.PandaForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-07-2018
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
@Controller("/showPandaDetail")
public class ShowPandaDetailAction extends Action {
	/*
	 * Generated Methods
	 */
	private static final Logger log = LoggerFactory.getLogger(SearchPandaAction.class);							
	
	@Autowired
	@Qualifier("pandaService")
	private SearchPandaService searchPandaService;
	
	public SearchPandaService getSearchPandaService() {
		return searchPandaService;
	}

	public void setSearchPandaService(SearchPandaService searchPandaService) {
		System.out.println("是否初始化创建searchPandaService");
		this.searchPandaService = searchPandaService;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String zid = (String) request.getParameter("zid");
		if(zid == null || zid.isEmpty()){
			return mapping.findForward("modifyPanda");
		}
		
		
		//会有panda的nullpointerException
		PandaForm pandaForm = new PandaForm(searchPandaService.findPandaByZid(zid));
		
		//pandaForm.pandaToPandaForm(searchPandaService.findPandaByZid(zid));
		
		request.setAttribute("panda", pandaForm);
		
		return mapping.findForward("detailPanda");
		
	}
}